using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ErrorHandlingAudit;

/// <summary>
/// Static, syntax-level error-handling compliance checker for the errors-handling.md
/// convention. Deliberately avoids MSBuildWorkspace project loading (fragile/slow on this
/// environment, and not required to answer the four structural questions below) and instead
/// parses every *.cs file with a plain <see cref="CSharpSyntaxTree"/> and applies four
/// syntax-pattern rules:
///
///   A — DomainError/exception construction that bypasses a module's Errors.cs factory.
///   B — caught-and-swallowed exceptions (no ExternalMessage/FixMessage/log propagates).
///   C — DomainError sites whose ExternalMessage/FixMessage is never read anywhere reachable.
///   D — catch clauses / Result&lt;T&gt;.Err sites missing [ErrorCode]/[ErrorOutcome] tagging.
/// </summary>
internal static class Program
{
    private static readonly string[] DefaultExcludes =
    {
        "bin", "obj", "MostaqlK.UITests", "tools", ".git"
    };

    private static int Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.Error.WriteLine("Usage: ErrorHandlingAudit <rootDir> [--out <file.md>] [--include-fixtures]");
            return 1;
        }

        var root = Path.GetFullPath(args[0]);
        string? outPath = null;
        var includeFixtures = false;

        for (var i = 1; i < args.Length; i++)
        {
            if (args[i] == "--out" && i + 1 < args.Length)
            {
                outPath = args[++i];
            }
            else if (args[i] == "--include-fixtures")
            {
                includeFixtures = true;
            }
        }

        var files = Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories)
            .Where(f => !IsExcluded(f, root, includeFixtures))
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var violations = new List<Violation>();
        foreach (var file in files)
        {
            var text = File.ReadAllText(file);
            var tree = CSharpSyntaxTree.ParseText(text, path: file);
            var root2 = tree.GetRoot();
            violations.AddRange(RuleA.Check(file, root2));
            violations.AddRange(RuleB.Check(file, root2));
            violations.AddRange(RuleC.Check(file, root2));
            violations.AddRange(RuleD.Check(file, root2));
        }

        violations = violations
            .OrderBy(v => v.File, StringComparer.OrdinalIgnoreCase)
            .ThenBy(v => v.Line)
            .ToList();

        Console.WriteLine($"Scanned {files.Count} file(s), found {violations.Count} violation(s).");
        foreach (var group in violations.GroupBy(v => v.Rule).OrderBy(g => g.Key))
        {
            Console.WriteLine($"  {group.Key}: {group.Count()}");
        }

        foreach (var v in violations)
        {
            Console.WriteLine($"{Rel(v.File, root)}:{v.Line}  [{v.Rule}]  {v.Snippet}");
        }

        if (outPath != null)
        {
            WriteMarkdown(outPath, violations, root);
        }

        return 0;
    }

    private static bool IsExcluded(string file, string root, bool includeFixtures)
    {
        var rel = Path.GetRelativePath(root, file);
        var segments = rel.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        if (!includeFixtures && segments.Contains("Fixtures"))
        {
            return true;
        }

        foreach (var excl in DefaultExcludes)
        {
            if (segments.Any(s => string.Equals(s, excl, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }
        }

        return false;
    }

    private static string Rel(string file, string root) => Path.GetRelativePath(root, file).Replace('\\', '/');

    private static void WriteMarkdown(string outPath, List<Violation> violations, string root)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Error-Handling Audit");
        sb.AppendLine();
        sb.AppendLine($"Generated by `tools/ErrorHandlingAudit`. Total violations: **{violations.Count}**.");
        sb.AppendLine();
        sb.AppendLine("| File:Line | Rule | Snippet |");
        sb.AppendLine("|---|---|---|");
        foreach (var v in violations)
        {
            var snippet = v.Snippet.Replace("|", "\\|");
            sb.AppendLine($"| `{Rel(v.File, root)}:{v.Line}` | {v.Rule} | `{snippet}` |");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
    }
}

internal sealed record Violation(string File, int Line, string Rule, string Snippet);

internal static class SyntaxHelpers
{
    public static int LineOf(SyntaxNode node) =>
        node.SyntaxTree.GetLineSpan(node.Span).StartLinePosition.Line + 1;

    public static string OneLine(SyntaxNode node)
    {
        var text = node.ToString();
        var firstLine = text.Split('\n')[0].Trim();
        return firstLine.Length > 100 ? firstLine[..100] + "..." : firstLine;
    }

    public static string? EnclosingClassName(SyntaxNode node) =>
        node.Ancestors().OfType<ClassDeclarationSyntax>().FirstOrDefault()?.Identifier.Text;

    public static MethodDeclarationSyntax? EnclosingMethod(SyntaxNode node) =>
        node.Ancestors().OfType<MethodDeclarationSyntax>().FirstOrDefault();

    public static bool HasAttribute(MethodDeclarationSyntax? method, params string[] attributeNameFragments)
    {
        if (method == null)
        {
            return false;
        }

        var text = string.Join(" ", method.AttributeLists.Select(a => a.ToString()));
        return attributeNameFragments.Any(f => text.Contains(f, StringComparison.Ordinal));
    }
}

/// <summary>Rule A — DomainError/exception construction bypassing a module's Errors.cs factory.</summary>
internal static class RuleA
{
    public static IEnumerable<Violation> Check(string file, SyntaxNode root)
    {
        var fileName = Path.GetFileName(file);
        var isErrorsFile = fileName.EndsWith("Errors.cs", StringComparison.OrdinalIgnoreCase);

        foreach (var creation in root.DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
        {
            var typeName = TypeName(creation);
            var isDomainError = typeName is "DomainError" or "MostaqlK.Core.DomainError";
            var isException = typeName != null && typeName.EndsWith("Exception", StringComparison.Ordinal);

            if (!isDomainError && !isException)
            {
                continue;
            }

            var className = SyntaxHelpers.EnclosingClassName(creation);
            var isFactoryClass = className != null &&
                (className.EndsWith("Errors", StringComparison.Ordinal) || className.EndsWith("Exception", StringComparison.Ordinal));

            if (isErrorsFile || isFactoryClass)
            {
                continue;
            }

            yield return new Violation(file, SyntaxHelpers.LineOf(creation), "A-FactoryBypass", SyntaxHelpers.OneLine(creation));
        }
    }

    private static string? TypeName(BaseObjectCreationExpressionSyntax creation) =>
        creation switch
        {
            ObjectCreationExpressionSyntax o => o.Type.ToString(),
            ImplicitObjectCreationExpressionSyntax => InferFromContext(creation),
            _ => null,
        };

    private static string? InferFromContext(SyntaxNode creation)
    {
        // `new(...)` target-typed creation — infer from the nearest return type / variable type.
        if (creation.Parent is ReturnStatementSyntax or ArrowExpressionClauseSyntax)
        {
            var method = SyntaxHelpers.EnclosingMethod(creation);
            return method?.ReturnType.ToString().Replace("Task<", "").TrimEnd('>');
        }

        if (creation.Parent is EqualsValueClauseSyntax { Parent: VariableDeclaratorSyntax { Parent: VariableDeclarationSyntax decl } })
        {
            return decl.Type.ToString();
        }

        return null;
    }
}

/// <summary>Rule B — caught-and-swallowed exceptions.</summary>
internal static class RuleB
{
    public static IEnumerable<Violation> Check(string file, SyntaxNode root)
    {
        foreach (var catchClause in root.DescendantNodes().OfType<CatchClauseSyntax>())
        {
            var block = catchClause.Block;
            if (block == null)
            {
                continue;
            }

            var text = block.ToString();

            var rethrows = block.DescendantNodes().OfType<ThrowStatementSyntax>().Any();
            var logs = text.Contains("InteractionLogger", StringComparison.Ordinal);
            var propagatesMessage = text.Contains(".ExternalMessage", StringComparison.Ordinal) ||
                                     text.Contains(".FixMessage", StringComparison.Ordinal);
            // A `return ...Result<T>.Err(...)` hands the DomainError to the caller (which is
            // expected to read ExternalMessage/FixMessage further up) — not a swallow.
            var propagatesResultErr = block.DescendantNodes().OfType<InvocationExpressionSyntax>()
                .Any(inv => inv.Expression is MemberAccessExpressionSyntax { Name.Identifier.Text: "Err" });
            // An explicit [ErrorOutcome] tag on the enclosing method documents the swallow as
            // deliberate (e.g. Ignored on an expected-cancellation path) — exempt it, since the
            // whole point of the attribute is to make that intent auditable rather than silent.
            var explicitlyTagged = SyntaxHelpers.HasAttribute(SyntaxHelpers.EnclosingMethod(catchClause), "ErrorOutcome");

            if (rethrows || logs || propagatesMessage || propagatesResultErr || explicitlyTagged)
            {
                continue;
            }

            yield return new Violation(file, SyntaxHelpers.LineOf(catchClause), "B-SwallowedCatch", SyntaxHelpers.OneLine(catchClause));
        }
    }
}

/// <summary>Rule C — DomainError sites whose ExternalMessage/FixMessage is never read.</summary>
internal static class RuleC
{
    public static IEnumerable<Violation> Check(string file, SyntaxNode root)
    {
        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            if (!HasDomainErrorSite(method, out var siteNode))
            {
                continue;
            }

            var bodyText = (method.Body?.ToString() ?? method.ExpressionBody?.ToString()) ?? string.Empty;

            var reads = bodyText.Contains(".ExternalMessage", StringComparison.Ordinal) ||
                        bodyText.Contains(".FixMessage", StringComparison.Ordinal) ||
                        bodyText.Contains("InteractionLogger", StringComparison.Ordinal) ||
                        bodyText.Contains("LabelWithSubText", StringComparison.Ordinal) ||
                        bodyText.Contains("ValidationMessage", StringComparison.Ordinal);

            if (reads)
            {
                continue;
            }

            if (PropagatesDirectly(method))
            {
                continue;
            }

            yield return new Violation(file, SyntaxHelpers.LineOf(siteNode!), "C-UnreadMessage", SyntaxHelpers.OneLine(siteNode!));
        }
    }

    private static bool HasDomainErrorSite(MethodDeclarationSyntax method, out SyntaxNode? site)
    {
        foreach (var param in method.ParameterList.Parameters)
        {
            if (param.Type?.ToString().Contains("DomainError", StringComparison.Ordinal) == true)
            {
                site = param;
                return true;
            }
        }

        foreach (var local in method.DescendantNodes().OfType<VariableDeclarationSyntax>())
        {
            if (local.Type.ToString().Contains("DomainError", StringComparison.Ordinal))
            {
                site = local;
                return true;
            }
        }

        foreach (var creation in method.DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
        {
            if (creation is ObjectCreationExpressionSyntax { Type: { } t } && t.ToString().Contains("DomainError", StringComparison.Ordinal))
            {
                site = creation;
                return true;
            }
        }

        foreach (var invocation in method.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            if (IsErrorsFactoryCall(invocation) || IsResultErrCall(invocation))
            {
                site = invocation;
                return true;
            }
        }

        site = null;
        return false;
    }

    private static bool IsErrorsFactoryCall(InvocationExpressionSyntax invocation)
    {
        if (invocation.Expression is not MemberAccessExpressionSyntax member)
        {
            return false;
        }

        var target = member.Expression.ToString();
        var lastSegment = target.Split('.').Last();
        return lastSegment.EndsWith("Errors", StringComparison.Ordinal);
    }

    private static bool IsResultErrCall(InvocationExpressionSyntax invocation)
    {
        if (invocation.Expression is not MemberAccessExpressionSyntax { Name.Identifier.Text: "Err" })
        {
            return false;
        }

        return true;
    }

    /// <summary>
    /// Exempts sites where the DomainError/Result flows straight to a `return`/`throw` of the
    /// same value (or of the very invocation that produced it) — the message is being handed to
    /// the caller, not dropped locally.
    /// </summary>
    private static bool PropagatesDirectly(MethodDeclarationSyntax method)
    {
        foreach (var ret in method.DescendantNodes().OfType<ReturnStatementSyntax>())
        {
            if (ret.Expression is IdentifierNameSyntax or InvocationExpressionSyntax or BaseObjectCreationExpressionSyntax)
            {
                return true;
            }
        }

        if (method.ExpressionBody?.Expression is IdentifierNameSyntax or InvocationExpressionSyntax or BaseObjectCreationExpressionSyntax)
        {
            return true;
        }

        foreach (var thr in method.DescendantNodes().OfType<ThrowStatementSyntax>())
        {
            if (thr.Expression is IdentifierNameSyntax or InvocationExpressionSyntax or BaseObjectCreationExpressionSyntax)
            {
                return true;
            }
        }

        return false;
    }
}

/// <summary>Rule D — catch clauses / Result&lt;T&gt;.Err sites missing [ErrorCode]/[ErrorOutcome] tagging.</summary>
internal static class RuleD
{
    public static IEnumerable<Violation> Check(string file, SyntaxNode root)
    {
        foreach (var catchClause in root.DescendantNodes().OfType<CatchClauseSyntax>())
        {
            var method = SyntaxHelpers.EnclosingMethod(catchClause);
            if (!SyntaxHelpers.HasAttribute(method, "ErrorCode", "ErrorOutcome"))
            {
                yield return new Violation(file, SyntaxHelpers.LineOf(catchClause), "D-MissingTag", SyntaxHelpers.OneLine(catchClause));
            }
        }

        foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            if (invocation.Expression is not MemberAccessExpressionSyntax { Name.Identifier.Text: "Err" })
            {
                continue;
            }

            // Skip Err sites already covered by an enclosing catch clause (avoid double counting).
            if (invocation.Ancestors().OfType<CatchClauseSyntax>().Any())
            {
                continue;
            }

            var method = SyntaxHelpers.EnclosingMethod(invocation);
            if (!SyntaxHelpers.HasAttribute(method, "ErrorCode", "ErrorOutcome"))
            {
                yield return new Violation(file, SyntaxHelpers.LineOf(invocation), "D-MissingTag", SyntaxHelpers.OneLine(invocation));
            }
        }
    }
}
